### ISSUE TITLE
Tests and Test Coverage implementation

### ISSUE THREAD

**Issue by JanisJ22** [ChristofferTan/csc207-project#24]
We are initiating the implementation of tests for our project to ensure the reliability and correctness of our code. This is a critical step in the development process to catch potential issues before the presentation.

**Tasks:**
- [x] Implement unit tests.
- [x] Prioritize test coverage for critical and frequently used parts of the codebase.
- [x] Ensure that the implemented tests collectively cover at least 90% of the code.
- [ ] Make sure that all tests passed before the presentation.

**Deadline:** TBD

This issue marks the beginning of our test implementation efforts. Let's collaborate to build a robust testing foundation for our project.

**Comment by JanisJ22** [comment]
Similar to #23, do you guys think we can finish this by December 3rd?
